# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nD9wdIiSPWH8Uwa9VDWLef9Dyqli_YtX
"""

#1
l = float(input("Enter the width: "))
b = float(input("Enter the breadth: "))
print("The area is : ",l*b)

#2
l = float(input("Enter the Height(in metres): "))
b = float(input("Enter the Weight: "))
print("The BMI is : ",b/(l**2))

#3
dict = {}
n = int(input("Enter the number of Students"))
for i in range(n):
  name = input("Enter the Name of student")
  marks = input("Enter the marks of student")
  dict[name] = marks

for key,value in dict.items():
  print(key,"'s marks is:",value)

#4
n = int(input("enter your age: "))
if n<18 and n>0:
  print("You are a minor")
elif n>=18 and n<=50:
  print("You are an adult")
elif n>50:
  print("You are a senior")
else:
  print("invalid age")

#5
for i in range(50):
  print(i+1,end=",")

#6
password = "password"
a=''
while(a!=password):
  a = input("enter the password: ")

#7
a = [1,2,5,6,7]
def avg(list):
  return sum(list)/len(list)

print(avg(a))

#8
str = "Hello guys"
count = 0
for i in str:
  str = str.lower()
  if i in ['a','e','i','o','u']:
    count+=1

print("number of vowels in",str,"is",count)

#9
import datetime as dt
print(dt.datetime.now())

#10
a = input()
b = input()
try:
  c = a+b
except Exception as e:
  print(e,"occured")

#11
try:
  a = int(input("enter a number: "))
except ValueError:
  print("Value error has occured")

#12
try:
  a = int(input("Enter dividend :"))
  b = int(input("Enter divisor: "))
  c = a/b
except ZeroDivisionError:
  print("Zero division error has occured")

#13
a = open("sample.txt",'w')
a.write("Hello,Python!")

#14
b = open("sample.txt",'r')
print(b.read())

#15
c = open("sample.txt",'a')
c.writelines("\nThis is new")
c.close()
x = open("sample.txt",'r')
print(x.read())

